# Generated by Django 4.2.11 on 2024-04-07 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuw', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactForm',
        ),
    ]
