# Generated by Django 4.2.11 on 2024-04-07 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuw', '0002_rename_contact_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
