# Generated by Django 4.2.11 on 2024-04-12 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuw', '0004_age_contact_over'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='over',
        ),
        migrations.DeleteModel(
            name='Age',
        ),
    ]
