# Generated by Django 4.2.11 on 2024-04-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuw', '0006_contact_availability_contact_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='availability',
            field=models.DateField(),
        ),
    ]
