# Generated by Django 4.2.11 on 2024-04-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuw', '0008_alter_contact_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='availability',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='questions',
            field=models.TextField(default=''),
        ),
    ]
