# Generated by Django 4.2.11 on 2024-04-13 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kuw', '0010_contact_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='questions',
        ),
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='availability',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
