# Generated by Django 4.2.11 on 2024-04-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuw', '0011_remove_contact_questions_contact_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created',)},
        ),
    ]
